; S.A.I Satellite Node Firmware
; Platform: ESP32-S3-DevKitC-1 (N8R8)

[env:satellite]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
lib_extra_dirs = ../shared/lib    ; sai_config / sai_led / sai_audio (sai_bt는 사용 안 함)
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DSAI_NODE_ROLE=1          ; 1 = SATELLITE
    -DSAI_VERSION=\"0.1.0\"

lib_deps =
    fastled/FastLED
